### ISSUE TITLE
xmlrpc.client.Fault: <Fault 1: "<class 'OverflowError'>:int exceeds XML-RPC limits">

### ISSUE THREAD

**Issue by Icecoke-ops** [SparksFlying/STLD#1]
我在运行这个代码时出现了问题：
Traceback (most recent call last):
  File "DAP.py", line 13, in <module>
    pk = phe.PaillierPublicKey(CA_server.getPub())
  File "/home/zh/.anaconda3/envs/mll/lib/python3.8/xmlrpc/client.py", line 1109, in __call__
    return self.__send(self.__name, args)
  File "/home/zh/.anaconda3/envs/mll/lib/python3.8/xmlrpc/client.py", line 1450, in __request
    response = self.__transport.request(
  File "/home/zh/.anaconda3/envs/mll/lib/python3.8/xmlrpc/client.py", line 1153, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/home/zh/.anaconda3/envs/mll/lib/python3.8/xmlrpc/client.py", line 1169, in single_request
    return self.parse_response(resp)
  File "/home/zh/.anaconda3/envs/mll/lib/python3.8/xmlrpc/client.py", line 1341, in parse_response
    return u.close()
  File "/home/zh/.anaconda3/envs/mll/lib/python3.8/xmlrpc/client.py", line 655, in close
    raise Fault(**self._stack[0])
xmlrpc.client.Fault: <Fault 1: "<class 'OverflowError'>:int exceeds XML-RPC limits">
conda: Python 3.8.16 (default, Mar  2 2023, 03:21:46) 
依赖环境与要求一致

**Comment by SparksFlying** [comment]
这是由于Python xmlrpc库未支持对大整数的支持，可以选择将Python安装目录下Lib/xmlrpc/client.py第538-539行注释避免抛出异常


张亮
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SparksFlying/STLD"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月21日(星期五) 晚上9:43
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[SparksFlying/STLD] xmlrpc.client.Fault: <Fault 1: "<class 'OverflowError'&gt;:int exceeds XML-RPC limits"&gt; (Issue #1)





 
我在运行这个代码时出现了问题：
 Traceback (most recent call last):
 File "DAP.py", line 13, in 
 pk = phe.PaillierPublicKey(CA_server.getPub())
 File "/home/zh/.anaconda3/envs/mll/lib/python3.8/xmlrpc/client.py", line 1109, in call
 return self.__send(self.__name, args)
 File "/home/zh/.anaconda3/envs/mll/lib/python3.8/xmlrpc/client.py", line 1450, in __request
 response = self.__transport.request(
 File "/home/zh/.anaconda3/envs/mll/lib/python3.8/xmlrpc/client.py", line 1153, in request
 return self.single_request(host, handler, request_body, verbose)
 File "/home/zh/.anaconda3/envs/mll/lib/python3.8/xmlrpc/client.py", line 1169, in single_request
 return self.parse_response(resp)
 File "/home/zh/.anaconda3/envs/mll/lib/python3.8/xmlrpc/client.py", line 1341, in parse_response
 return u.close()
 File "/home/zh/.anaconda3/envs/mll/lib/python3.8/xmlrpc/client.py", line 655, in close
 raise Fault(**self._stack[0])
 xmlrpc.client.Fault: <Fault 1: "<class 'OverflowError'&gt;:int exceeds XML-RPC limits"&gt;
 conda: Python 3.8.16 (default, Mar  2 2023, 03:21:46)
 依赖环境与要求一致

**Comment by CafeBabe202** [comment]
非常感谢你的帮助，我现在已经解决了这个问题，但是在继续执行时有一个文件没有找到，请问能提供一下吗？或者描述一下文件的内容格式，我来自己创建一下

**Comment by Icecoke-ops** [comment]
> 这是由于Python xmlrpc库未支持对大整数的支持，可以选择将Python安装目录下Lib/xmlrpc/client.py第538-539行注释避免抛出异常 张亮 ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "SparksFlying/STLD" ***@***.***&gt;; 发送时间:&nbsp;2023年4月21日(星期五) 晚上9:43 ***@***.***&gt;; ***@***.***&gt;; 主题:&nbsp;[SparksFlying/STLD] xmlrpc.client.Fault: <Fault 1: "<class 'OverflowError'&gt;:int exceeds XML-RPC limits"&gt; (Issue #1) 我在运行这个代码时出现了问题： Traceback (most recent call last): File "DAP.py", line 13, in pk = phe.PaillierPublicKey(CA_server.getPub()) File "/home/zh/.anaconda3/envs/mll/lib/python3.8/xmlrpc/client.py", line 1109, in call return self.__send(self.__name, args) File "/home/zh/.anaconda3/envs/mll/lib/python3.8/xmlrpc/client.py", line 1450, in __request response = self.__transport.request( File "/home/zh/.anaconda3/envs/mll/lib/python3.8/xmlrpc/client.py", line 1153, in request return self.single_request(host, handler, request_body, verbose) File "/home/zh/.anaconda3/envs/mll/lib/python3.8/xmlrpc/client.py", line 1169, in single_request return self.parse_response(resp) File "/home/zh/.anaconda3/envs/mll/lib/python3.8/xmlrpc/client.py", line 1341, in parse_response return u.close() File "/home/zh/.anaconda3/envs/mll/lib/python3.8/xmlrpc/client.py", line 655, in close raise Fault(**self._stack[0]) xmlrpc.client.Fault: <Fault 1: "<class 'OverflowError'&gt;:int exceeds XML-RPC limits"&gt; conda: Python 3.8.16 (default, Mar 2 2023, 03:21:46) 依赖环境与要求一致 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

非常感谢你的帮助，我现在已经解决了这个问题，但是在继续执行时有一个文件没有找到，请问能提供一下吗？或者描述一下文件的内容格式，我来自己创建一下。
具体报错信息如下：
FileNotFoundError: [Errno 2] No such file or directory: 'data/test_2_12_rtree.txt'

**Comment by SparksFlying** [comment]
张亮
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SparksFlying/STLD"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月25日(星期二) 晚上8:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [SparksFlying/STLD] xmlrpc.client.Fault: <Fault 1: "<class 'OverflowError'&gt;:int exceeds XML-RPC limits"&gt; (Issue #1)





  
这是由于Python xmlrpc库未支持对大整数的支持，可以选择将Python安装目录下Lib/xmlrpc/client.py第538-539行注释避免抛出异常 张亮 @.*** &nbsp;
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "SparksFlying/STLD" @.&gt;; 发送时间:&nbsp;2023年4月21日(星期五) 晚上9:43 @.&gt;; @.**&gt;; 主题:&nbsp;[SparksFlying/STLD] xmlrpc.client.Fault: <Fault 1: "<class 'OverflowError'&gt;:int exceeds XML-RPC limits"&gt; (Issue #1) 我在运行这个代码时出现了问题： Traceback (most recent call last): File "DAP.py", line 13, in pk = phe.PaillierPublicKey(CA_server.getPub()) File "/home/zh/.anaconda3/envs/mll/lib/python3.8/xmlrpc/client.py", line 1109, in call return self.__send(self.__name, args) File "/home/zh/.anaconda3/envs/mll/lib/python3.8/xmlrpc/client.py", line 1450, in __request response = self.__transport.request( File "/home/zh/.anaconda3/envs/mll/lib/python3.8/xmlrpc/client.py", line 1153, in request return self.single_request(host, handler, request_body, verbose) File "/home/zh/.anaconda3/envs/mll/lib/python3.8/xmlrpc/client.py", line 1169, in single_request return self.parse_response(resp) File "/home/zh/.anaconda3/envs/mll/lib/python3.8/xmlrpc/client.py", line 1341, in parse_response return u.close() File "/home/zh/.anaconda3/envs/mll/lib/python3.8/xmlrpc/client.py", line 655, in close raise Fault(self._stack[0]) xmlrpc.client.Fault: <Fault 1: "<class 'OverflowError'&gt;:int exceeds XML-RPC limits"&gt; conda: Python 3.8.16 (default, Mar 2 2023, 03:21:46) 依赖环境与要求一致 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.&gt;
  
非常感谢你的帮助，我现在已经解决了这个问题，但是在继续执行时有一个文件没有找到，请问能提供一下吗？或者描述一下文件的内容格式，我来自己创建一下。
 具体报错信息如下：
 FileNotFoundError: [Errno 2] No such file or directory: 'data/test_2_12_rtree.txt'

**Comment by maliliym** [comment]
请问这个secure top-k skyline query protocol存储库有对应的文章吗？有的话在哪里可以找到呢
